openapi: 3.0.0
info:
  title: Get Products API
  description: API endpoint for retrieving a list of products from the system.
  version: 1.0.0
paths:
  /products:
    get:
      summary: Retrieve a list of products
      description: This endpoint allows you to retrieve all products in the system.
      parameters:
        - name: page
          in: query
          required: false
          description: The page number for pagination.
          schema:
            type: integer
            example: 1
        - name: limit
          in: query
          required: false
          description: The number of products to return per page.
          schema:
            type: integer
            example: 10
      responses:
        '200':
          description: A list of products retrieved successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  products:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                          description: The ID of the product.
                          example: 1
                        name:
                          type: string
                          example: "Laptop"
                        description:
                          type: string
                          example: "A high-performance laptop."
                        price:
                          type: number
                          format: float
                          example: 999.99
                        stock:
                          type: integer
                          example: 50
                  total:
                    type: integer
                    description: The total number of products available.
                    example: 100
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "An error occurred while retrieving products"