openapi: 3.0.0
info:
  title: User Login API
  description: API endpoint for user login in the system.
  version: 1.0.0
paths:
  /users/login:
    post:
      summary: Login a user
      description: This endpoint allows an existing user to log in by providing their email and password.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The email address of the user.
                  example: "john.doe@example.com"
                password:
                  type: string
                  description: The password for the user account.
                  example: "securepassword123"
      responses:
        '200':
          description: User logged in successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
                    description: Authentication token for the user session.
                    example: "eyJhbGciOiJIUzI1NiIsInR..."
                  user:
                    type: object
                    properties:
                      id:
                        type: integer
                        description: The ID of the logged-in user.
                        example: 1
                      name:
                        type: string
                        example: "John Doe"
                      email:
                        type: string
                        example: "john.doe@example.com"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid email or password"
        '401':
          description: Unauthorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid credentials"