openapi: 3.0.0
info:
  title: Update User API
  description: API endpoint for updating an existing user's information.
  version: 1.0.0
paths:
  /users/{id}:
    put:
      summary: Update user information
      description: This endpoint allows updating the information of an existing user specified by their ID.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the user to update.
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: The new name of the user.
                  example: "John Smith"
                email:
                  type: string
                  description: The new email address of the user.
                  example: "john.smith@example.com"
      responses:
        '200':
          description: User information updated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    description: The ID of the updated user.
                    example: 1
                  name:
                    type: string
                    example: "John Smith"
                  email:
                    type: string
                    example: "john.smith@example.com"
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "Invalid input data"
        '404':
          description: User not found
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: "User not found"